/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minesweeper;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Adrian
 */
public class MinesweeperUI extends javax.swing.JFrame {

    /**
     * Creates new form MinesweeperUI
     */
    public MinesweeperUI() {
        initComponents();
        initMyComponents();
        StartGameBtnActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RuleLbl = new javax.swing.JLabel();
        Rule = new javax.swing.JTextField();
        StartGameBtn = new javax.swing.JButton();
        StepForwardBtn = new javax.swing.JButton();
        BoardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        RuleLbl.setText("Rule");

        StartGameBtn.setText("New Game");
        StartGameBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StartGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBtnActionPerformed(evt);
            }
        });

        StepForwardBtn.setText("Step Forward");
        StepForwardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepForwardBtnActionPerformed(evt);
            }
        });

        BoardPanel.setPreferredSize(new java.awt.Dimension(960, 520));
        BoardPanel.setLayout(new java.awt.GridLayout(16, 5, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RuleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rule, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(263, 263, 263))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(StartGameBtn)
                                .addGap(438, 438, 438))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(StepForwardBtn)
                                .addGap(429, 429, 429))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(StartGameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(StepForwardBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RuleLbl))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMyComponents()
    {
        game = new Minesweeper();
        Board = new MinesweeperButton[16][30];
        for (int i = 0; i < 16; i++)
        {
            for (int j = 0; j < 30; j++)
            {
                Board[i][j] = new MinesweeperButton(i,j);
                //Board[i][j].setPreferredSize(new Dimension(20,20));
                Board[i][j].setFont(new Font("Arial", Font.PLAIN, 8));
                Board[i][j].addActionListener(cellClick);
                BoardPanel.add(Board[i][j]);
            }
        }
        add(BoardPanel);
    }
    
    
    
    
    private void StartGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartGameBtnActionPerformed
    
    
    
    private void StepForwardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepForwardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StepForwardBtnActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinesweeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinesweeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinesweeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinesweeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinesweeperUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JTextField Rule;
    private javax.swing.JLabel RuleLbl;
    private javax.swing.JButton StartGameBtn;
    private javax.swing.JButton StepForwardBtn;
    // End of variables declaration//GEN-END:variables
    private MinesweeperButton[][] Board;
    private Minesweeper game;
    
    private final ActionListener cellClick = new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent ae)
        {
            String valueOfCell;
            MinesweeperButton cell = (MinesweeperButton) ae.getSource();
            valueOfCell = game.clickCell(cell.x,cell.y);
            cell.setText(valueOfCell);
            cell.setEnabled(false);
        }
    };
    
}
